# Generated by Django 4.2.4 on 2023-08-14 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productsave_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_alter_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivaryuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField()),
                ('landmark', models.CharField(max_length=250)),
                ('twon_or_city', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productsave')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
