# Generated by Django 4.2.4 on 2023-08-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_delivaryuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='contsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('textarea', models.CharField(max_length=255)),
            ],
        ),
    ]
