# Generated by Django 4.2.4 on 2023-08-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_contsave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contsave',
            old_name='address',
            new_name='email',
        ),
    ]
