# Generated by Django 4.2.4 on 2023-08-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='codsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(max_length=100)),
                ('deluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.delivaryuser')),
            ],
        ),
    ]
