# Generated by Django 4.2.4 on 2023-08-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_codsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='razorpaydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_paymentrazorpay', models.CharField(max_length=100)),
                ('deluserrazorpay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.delivaryuser')),
            ],
        ),
    ]
