# Generated by Django 4.2.4 on 2023-08-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_razorpaydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaydb',
            name='paymentid',
            field=models.IntegerField(null=True),
        ),
    ]
