# Generated by Django 3.2.10 on 2023-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorysave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(blank=True, max_length=30, null=True)),
                ('categoryimage', models.ImageField(upload_to='profile')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
