# Generated by Django 3.2.10 on 2023-07-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procategoryname', models.CharField(blank=True, max_length=60, null=True)),
                ('productname', models.CharField(blank=True, max_length=60, null=True)),
                ('proquantity', models.IntegerField(blank=True, null=True)),
                ('proprice', models.IntegerField(blank=True, null=True)),
                ('productimage', models.ImageField(upload_to='productimage')),
                ('prodescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
