# Generated by Django 3.2.10 on 2023-07-24 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
