# Generated by Django 4.2.4 on 2023-09-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productsave_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsave',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsave',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
